# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cloud_controller.proto

require 'google/protobuf'

require 'common_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "api.Route" do
    optional :guid, :string, 1
    optional :host, :string, 2
  end
  add_message "api.UpsertRouteRequest" do
    optional :route, :message, 1, "api.Route"
  end
  add_message "api.UpsertRouteResponse" do
  end
  add_message "api.DeleteRouteRequest" do
    optional :guid, :string, 1
  end
  add_message "api.DeleteRouteResponse" do
  end
  add_message "api.CapiProcess" do
    optional :guid, :string, 1
    optional :diego_process_guid, :string, 2
  end
  add_message "api.RouteMapping" do
    optional :capi_process, :message, 1, "api.CapiProcess"
    optional :route_guid, :string, 2
  end
  add_message "api.MapRouteRequest" do
    optional :route_mapping, :message, 1, "api.RouteMapping"
  end
  add_message "api.MapRouteResponse" do
  end
  add_message "api.UnmapRouteRequest" do
    optional :capi_process_guid, :string, 1
    optional :route_guid, :string, 2
  end
  add_message "api.UnmapRouteResponse" do
  end
end

module Api
  Route = Google::Protobuf::DescriptorPool.generated_pool.lookup("api.Route").msgclass
  UpsertRouteRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("api.UpsertRouteRequest").msgclass
  UpsertRouteResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("api.UpsertRouteResponse").msgclass
  DeleteRouteRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("api.DeleteRouteRequest").msgclass
  DeleteRouteResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("api.DeleteRouteResponse").msgclass
  CapiProcess = Google::Protobuf::DescriptorPool.generated_pool.lookup("api.CapiProcess").msgclass
  RouteMapping = Google::Protobuf::DescriptorPool.generated_pool.lookup("api.RouteMapping").msgclass
  MapRouteRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("api.MapRouteRequest").msgclass
  MapRouteResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("api.MapRouteResponse").msgclass
  UnmapRouteRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("api.UnmapRouteRequest").msgclass
  UnmapRouteResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("api.UnmapRouteResponse").msgclass
end
