# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: cloud_controller.proto for package 'api'

require 'grpc'
require 'cloud_controller_pb'

module Api
  module CloudControllerCopilot
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'api.CloudControllerCopilot'

      rpc :UpsertRoute, UpsertRouteRequest, UpsertRouteResponse
      rpc :DeleteRoute, DeleteRouteRequest, DeleteRouteResponse
      rpc :MapRoute, MapRouteRequest, MapRouteResponse
      rpc :UnmapRoute, UnmapRouteRequest, UnmapRouteResponse
      rpc :Health, HealthRequest, HealthResponse
    end

    Stub = Service.rpc_stub_class
  end
end
