# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: cloud_controller_future.proto for package 'cloudfoundry.copilot.protos'

require 'grpc'
require 'cloud_controller_future_pb'

module Cloudfoundry
  module Copilot
    module Protos
      module CloudControllerCopilotFuture
        class Service

          include GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'cloudfoundry.copilot.protos.CloudControllerCopilotFuture'

          rpc :UpsertRoute, UpsertRouteRequest, UpsertRouteResponse
          rpc :DeleteRoute, DeleteRouteRequest, DeleteRouteResponse
          rpc :UpsertCapiProcess, UpsertCapiProcessRequest, UpsertCapiProcessResponse
          rpc :DeleteCapiProcess, DeleteCapiProcessRequest, DeleteCapiProcessResponse
          rpc :MapRoute, MapRouteRequest, MapRouteResponse
          rpc :UnmapRoute, UnmapRouteRequest, UnmapRouteResponse
          rpc :BulkSync, BulkSyncRequest, BulkSyncResponse
        end

        Stub = Service.rpc_stub_class
      end
    end
  end
end
