---
openapi: 3.0.3
info:
  title: Cloud Controller V3 API
  version: v3
servers: []
paths:
  "/healthz":
    get:
      summary: GET /healthz
      responses:
        '200':
          description: returns a 200
