# Cloud Controller Specific Rubocop Config

plugins:
  - rubocop-sequel
  - rubocop-rails
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-rspec
  - rubocop-rspec_rails

require:
  - ./spec/linters/migration/add_constraint_name.rb
  - ./spec/linters/migration/include_string_size.rb
  - ./spec/linters/migration/require_primary_key.rb
  - ./spec/linters/match_requires_with_includes.rb
  - ./spec/linters/prefer_oj_over_other_json_libraries.rb


#### BASE SECTION
AllCops:
  TargetRubyVersion: 3.2
  Exclude:
    - lib/diego/bbs/models/**/*_pb.rb
    - lib/locket/**/*_pb.rb
    - lib/logcache/**/*_pb.rb
    - lib/loggregator-api/**/*_pb.rb
    - vendor/bundle/**/*


#### CUSTOMIZED SECTION
Layout/DotPosition:
  EnforcedStyle: trailing
Layout/EmptyLineBetweenDefs:
  EmptyLineBetweenClassDefs: false
Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent
Layout/LineLength:
  Max: 180
Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space
Metrics/BlockLength:
  Exclude:
    - !ruby/regexp /db/migrations/201([0-9]).+\.rb$/
    - !ruby/regexp /db/migrations/202([0-5]).+\.rb$/
    - config/routes.rb
    - lib/tasks/db.rake
    - lib/tasks/jobs.rake
  Max: 50
Metrics/CyclomaticComplexity:
  Max: 12
Metrics/MethodLength:
  Max: 60
Metrics/ModuleLength:
  Exclude:
    - spec/**/*
  Max: 200
Migration/AddConstraintName: # Exclude for old Migrations
  Include:
    - db/migrations/**/*
  Exclude:
    - !ruby/regexp /db/migrations/201([0-9]).+\.rb$/
    - !ruby/regexp /db/migrations/202([0-2]).+\.rb$/
Migration/IncludeStringSize: # Exclude for old Migrations
  Include:
    - db/migrations/**/*
  Exclude:
    - !ruby/regexp /db/migrations/201([0-9]).+\.rb$/
    - !ruby/regexp /db/migrations/202([0-2]).+\.rb$/
Migration/RequirePrimaryKey: # Exclude for old Migrations
  Include:
    - db/migrations/**/*
  Exclude:
    - !ruby/regexp /db/migrations/201([0-9]).+\.rb$/
Naming/MethodParameterName:
  AllowedNames:
    - e
    - id
    - by
    - 'on'
    - at
    - db
  AllowNamesEndingInNumbers: true
  MinNameLength: 3
Rails/Blank: # Alters logic if NilOrEmpty is true
  NilOrEmpty: false
Rails/HttpPositionalArguments: # Breaks Code for specs as it's not rails used there it's a test framework (racktest)
  Exclude:
    - spec/**/*
Rails/Output: # Exclude for blobstore benchmark
  Exclude:
    - lib/cloud_controller/benchmark/blobstore.rb
Rails/Present:  # Alters logic if NotNilAndNotEmpty is true
  NotNilAndNotEmpty: false
Rails/SkipsModelValidations: # We don't want any model at all in migrations and migration specs
  Exclude:
    - db/migrations/**/*
    - spec/migrations/**/*
Sequel/ConcurrentIndex:
  Exclude:
    - !ruby/regexp /db/migrations/201([0-9]).+\.rb$/
    - !ruby/regexp /db/migrations/202([0-3]).+\.rb$/
Sequel/IrreversibleMigration:
  Exclude:
    - !ruby/regexp /db/migrations/201([0-9]).+\.rb$/
    - !ruby/regexp /db/migrations/202([0-3]).+\.rb$/
Style/Alias:
  EnforcedStyle: prefer_alias_method
Style/ExpandPathArguments:
  Exclude:
    - !ruby/regexp /db/migrations/201([0-9]).+\.rb$/
Style/FormatString:
  EnforcedStyle: sprintf
Style/HashSyntax:
  EnforcedShorthandSyntax: consistent
Style/RaiseArgs:
  EnforcedStyle: compact


#### ENABLED SECTION
Capybara/ClickLinkOrButtonStyle:
  Enabled: true
Capybara/FindAllFirst:
  Enabled: true
Capybara/MatchStyle:
  Enabled: true
Capybara/NegationMatcher:
  Enabled: true
Capybara/NegationMatcherAfterVisit:
  Enabled: true
Capybara/RedundantWithinFind:
  Enabled: true
Capybara/RSpec/HaveSelector:
  Enabled: true
Capybara/RSpec/PredicateMatcher:
  Enabled: true
Capybara/SpecificActions:
  Enabled: true
Capybara/SpecificFinders:
  Enabled: true
Capybara/SpecificMatcher:
  Enabled: true
FactoryBot/AssociationStyle:
  Enabled: true
FactoryBot/ConsistentParenthesesStyle:
  Enabled: true
FactoryBot/ExcessiveCreateList:
  Enabled: true
FactoryBot/FactoryAssociationWithStrategy:
  Enabled: true
FactoryBot/FactoryNameStyle:
  Enabled: true
FactoryBot/IdSequence:
  Enabled: true
FactoryBot/RedundantFactoryOption:
  Enabled: true
FactoryBot/SyntaxMethods:
  Enabled: true
Gemspec/AddRuntimeDependency:
  Enabled: true
Gemspec/AttributeAssignment:
  Enabled: true
Gemspec/DeprecatedAttributeAssignment:
  Enabled: true
Gemspec/DevelopmentDependencies:
  Enabled: true
Gemspec/RequireMFA:
  Enabled: true
Layout/EmptyLinesAfterModuleInclusion:
  Enabled: true
Layout/LineContinuationLeadingSpace:
  Enabled: true
Layout/LineContinuationSpacing:
  Enabled: true
Layout/LineEndStringConcatenationIndentation:
  Enabled: true
Layout/SpaceBeforeBrackets:
  Enabled: true
Lint/AmbiguousAssignment:
  Enabled: true
Lint/AmbiguousOperatorPrecedence:
  Enabled: true
Lint/AmbiguousRange:
  Enabled: true
Lint/ArrayLiteralInRegexp:
  Enabled: true
Lint/ConstantDefinitionInBlock:
  Enabled: true
Lint/ConstantOverwrittenInRescue:
  Enabled: true
Lint/ConstantReassignment:
  Enabled: true
Lint/CopDirectiveSyntax:
  Enabled: true
Lint/DeprecatedConstants:
  Enabled: true
Lint/DuplicateBranch:
  Enabled: true
Lint/DuplicateMagicComment:
  Enabled: true
Lint/DuplicateMatchPattern:
  Enabled: true
Lint/DuplicateRegexpCharacterClassElement:
  Enabled: true
Lint/DuplicateSetElement:
  Enabled: true
Lint/EmptyBlock:
  Enabled: true
Lint/EmptyClass:
  Enabled: true
Lint/EmptyConditionalBody:
  Enabled: true
Lint/EmptyInPattern:
  Enabled: true
Lint/HashNewWithKeywordArgumentsAsDefault:
  Enabled: true
Lint/IncompatibleIoSelectWithFiberScheduler:
  Enabled: true
Lint/ItWithoutArgumentsInBlock:
  Enabled: true
Lint/LambdaWithoutLiteralBlock:
  Enabled: true
Lint/LiteralAssignmentInCondition:
  Enabled: true
Lint/MissingSuper:
  Enabled: true
Lint/MixedCaseRange:
  Enabled: true
Lint/NoReturnInBeginEndBlocks:
  Enabled: true
Lint/NonAtomicFileOperation:
  Enabled: true
Lint/NumberedParameterAssignment:
  Enabled: true
Lint/NumericOperationWithConstantResult:
  Enabled: true
Lint/OrAssignmentToConstant:
  Enabled: true
Lint/RedundantDirGlobSort:
  Enabled: true
Lint/RedundantRegexpQuantifiers:
  Enabled: true
Lint/RedundantTypeConversion:
  Enabled: true
Lint/RefinementImportMethods:
  Enabled: true
Lint/RequireRangeParentheses:
  Enabled: true
Lint/RequireRelativeSelfPath:
  Enabled: true
Lint/SharedMutableDefault:
  Enabled: true
Lint/SuppressedException:
  Enabled: true
Lint/SuppressedExceptionInNumberConversion:
  Enabled: true
Lint/SymbolConversion:
  Enabled: true
Lint/ToEnumArguments:
  Enabled: true
Lint/TripleQuotes:
  Enabled: true
Lint/UnescapedBracketInRegexp:
  Enabled: true
Lint/UnexpectedBlockArity:
  Enabled: true
Lint/UnifiedInteger:
  Enabled: true
Lint/UnmodifiedReduceAccumulator:
  Enabled: true
Lint/UnusedMethodArgument:
  Enabled: true
Lint/UselessConstantScoping:
  Enabled: true
Lint/UselessDefaultValueArgument:
  Enabled: true
Lint/UselessDefined:
  Enabled: true
Lint/UselessMethodDefinition:
  Enabled: true
Lint/UselessNumericOperation:
  Enabled: true
Lint/UselessOr:
  Enabled: true
Lint/UselessRescue:
  Enabled: true
Lint/UselessRuby2Keywords:
  Enabled: true
Metrics/AbcSize:
  Enabled: true
Metrics/ClassLength:
  Enabled: true
Metrics/CollectionLiteralLength:
  Enabled: true
Metrics/ParameterLists:
  Enabled: true
Metrics/PerceivedComplexity:
  Enabled: true
Naming/BlockForwarding:
  Enabled: true
Naming/FileName:
  Enabled: true
Naming/HeredocDelimiterNaming:
  Enabled: true
Naming/PredicateMethod:
  Enabled: true
Naming/PredicatePrefix:
  Enabled: true
Naming/VariableNumber:
  Enabled: true
Rails/ActionControllerFlashBeforeRender:
  Enabled: true
Rails/ActionControllerTestCase:
  Enabled: true
Rails/ActionOrder:
  Enabled: true
Rails/ActiveRecordAliases:
  Enabled: true
Rails/ActiveRecordCallbacksOrder:
  Enabled: true
Rails/ActiveSupportOnLoad:
  Enabled: true
Rails/AddColumnIndex:
  Enabled: true
Rails/AfterCommitOverride:
  Enabled: true
Rails/AttributeDefaultBlockValue:
  Enabled: true
Rails/CompactBlank:
  Enabled: true
Rails/DeprecatedActiveModelErrorsMethods:
  Enabled: true
Rails/DotSeparatedKeys:
  Enabled: true
Rails/DuplicateAssociation:
  Enabled: true
Rails/DuplicateScope:
  Enabled: true
Rails/DurationArithmetic:
  Enabled: true
Rails/EagerEvaluationLogMessage:
  Enabled: true
Rails/EnumSyntax:
  Enabled: true
Rails/EnvLocal:
  Enabled: true
Rails/ExpandedDateRange:
  Enabled: true
Rails/FindById:
  Enabled: true
Rails/FindByOrAssignmentMemoization:
  Enabled: true
Rails/FreezeTime:
  Enabled: true
Rails/HttpStatusNameConsistency:
  Enabled: true
Rails/I18nLazyLookup:
  Enabled: true
Rails/I18nLocaleAssignment:
  Enabled: true
Rails/IgnoredColumnsAssignment:
  Enabled: true
Rails/Inquiry:
  Enabled: true
Rails/MailerName:
  Enabled: true
Rails/MatchRoute:
  Enabled: true
Rails/MigrationClassName:
  Enabled: true
Rails/MultipleRoutePaths:
  Enabled: true
Rails/NegateInclude:
  Enabled: true
Rails/OrderArguments:
  Enabled: true
Rails/Pluck:
  Enabled: true
Rails/PluckInWhere:
  Enabled: true
Rails/RedirectBackOrTo:
  Enabled: true
Rails/RedundantPresenceValidationOnBelongsTo:
  Enabled: true
Rails/RedundantTravelBack:
  Enabled: true
Rails/RenderInline:
  Enabled: true
Rails/RenderPlainText:
  Enabled: true
Rails/ResponseParsedBody:
  Enabled: true
Rails/RootJoinChain:
  Enabled: true
Rails/RootPathnameMethods:
  Enabled: true
Rails/RootPublicPath:
  Enabled: true
Rails/SelectMap:
  Enabled: true
Rails/ShortI18n:
  Enabled: true
Rails/SquishedSQLHeredocs:
  Enabled: true
Rails/StripHeredoc:
  Enabled: true
Rails/StrongParametersExpect:
  Enabled: true
Rails/ThreeStateBooleanColumn:
  Enabled: true
Rails/TimeZone:
  Enabled: true
Rails/TimeZoneAssignment:
  Enabled: true
Rails/ToFormattedS:
  Enabled: true
Rails/ToSWithArgument:
  Enabled: true
Rails/TopLevelHashWithIndifferentAccess:
  Enabled: true
Rails/TransactionExitStatement:
  Enabled: true
Rails/UnusedIgnoredColumns:
  Enabled: true
Rails/UnusedRenderContent:
  Enabled: true
Rails/WhereEquals:
  Enabled: true
Rails/WhereExists:
  Enabled: true
Rails/WhereMissing:
  Enabled: true
Rails/WhereNot:
  Enabled: true
Rails/WhereNotWithMultipleConditions:
  Enabled: true
Rails/WhereRange:
  Enabled: true
RSpec/AnyInstance:
  Enabled: true
RSpec/Be:
  Enabled: true
RSpec/BeEmpty:
  Enabled: true
RSpec/BeEq:
  Enabled: true
RSpec/BeforeAfterAll:
  Enabled: true
RSpec/BeNil:
  Enabled: true
RSpec/ChangeByZero:
  Enabled: true
RSpec/ContainExactly:
  Enabled: true
RSpec/ContextWording:
  Enabled: true
RSpec/DescribeClass:
  Enabled: true
RSpec/DescribedClass:
  Enabled: true
RSpec/DuplicatedMetadata:
  Enabled: true
RSpec/EmptyExampleGroup:
  Enabled: true
RSpec/EmptyMetadata:
  Enabled: true
RSpec/Eq:
  Enabled: true
RSpec/ExampleLength:
  Enabled: true
RSpec/ExcessiveDocstringSpacing:
  Enabled: true
RSpec/ExpectActual:
  Enabled: true
RSpec/ExpectInHook:
  Enabled: true
RSpec/ExpectInLet:
  Enabled: true
RSpec/IdenticalEqualityAssertion:
  Enabled: true
RSpec/IncludeExamples:
  Enabled: true
RSpec/IndexedLet:
  Enabled: true
RSpec/InstanceVariable:
  Enabled: true
RSpec/IteratedExpectation:
  Enabled: true
RSpec/LeakyConstantDeclaration:
  Enabled: true
RSpec/LeakyLocalVariable:
  Enabled: true
RSpec/LetSetup:
  Enabled: true
RSpec/MatchArray:
  Enabled: true
RSpec/MessageChain:
  Enabled: true
RSpec/MessageSpies:
  Enabled: true
RSpec/MetadataStyle:
  Enabled: true
RSpec/MultipleDescribes:
  Enabled: true
RSpec/MultipleExpectations:
  Enabled: true
RSpec/MultipleMemoizedHelpers:
  Enabled: true
RSpec/NamedSubject:
  Enabled: true
RSpec/NestedGroups:
  Enabled: true
RSpec/NoExpectationExample:
  Enabled: true
RSpec/OverwritingSetup:
  Enabled: true
RSpec/PendingWithoutReason:
  Enabled: true
RSpec/ReceiveMessages:
  Enabled: true
RSpec/RedundantAround:
  Enabled: true
RSpec/RedundantPredicateMatcher:
  Enabled: true
RSpec/RemoveConst:
  Enabled: true
RSpec/RepeatedDescription:
  Enabled: true
RSpec/RepeatedExample:
  Enabled: true
RSpec/RepeatedExampleGroupBody:
  Enabled: true
RSpec/RepeatedExampleGroupDescription:
  Enabled: true
RSpec/ReturnFromStub:
  Enabled: true
RSpec/ScatteredLet:
  Enabled: true
RSpec/SkipBlockInsideExample:
  Enabled: true
RSpec/SortMetadata:
  Enabled: true
RSpec/SpecFilePathFormat:
  Enabled: true
RSpec/SpecFilePathSuffix:
  Enabled: true
RSpec/StubbedMock:
  Enabled: true
RSpec/SubjectDeclaration:
  Enabled: true
RSpec/SubjectStub:
  Enabled: true
RSpec/VariableName:
  Enabled: true
RSpec/VerifiedDoubleReference:
  Enabled: true
RSpec/VerifiedDoubles:
  Enabled: true
RSpec/VoidExpect:
  Enabled: true
RSpecRails/AvoidSetupHook:
  Enabled: true
RSpecRails/HaveHttpStatus:
  Enabled: true
RSpecRails/InferredSpecType:
  Enabled: true
RSpecRails/MinitestAssertions:
  Enabled: true
RSpecRails/NegationBeValid:
  Enabled: true
RSpecRails/TravelAround:
  Enabled: true
Security/CompoundHash:
  Enabled: true
Security/IoMethods:
  Enabled: true
Style/AmbiguousEndlessMethodDefinition:
  Enabled: true
Style/ArgumentsForwarding:
  Enabled: true
Style/ArrayIntersect:
  Enabled: true
Style/ArrayIntersectWithSingleElement:
  Enabled: true
Style/BitwisePredicate:
  Enabled: true
Style/CaseLikeIf:
  Enabled: true
Style/ClassAndModuleChildren:
  Enabled: true
Style/CollectionCompact:
  Enabled: true
Style/CollectionQuerying:
  Enabled: true
Style/CombinableDefined:
  Enabled: true
Style/CombinableLoops:
  Enabled: true
Style/ComparableBetween:
  Enabled: true
Style/ComparableClamp:
  Enabled: true
Style/ConcatArrayLiterals:
  Enabled: true
Style/DataInheritance:
  Enabled: true
Style/DigChain:
  Enabled: true
Style/DirEmpty:
  Enabled: true
Style/Documentation:
  Enabled: true
Style/DocumentDynamicEvalDefinition:
  Enabled: true
Style/DoubleNegation:
  Enabled: true
Style/EmptyClassDefinition:
  Enabled: true
Style/EmptyHeredoc:
  Enabled: true
Style/EmptyStringInsideInterpolation:
  Enabled: true
Style/Encoding:
  Enabled: true
Style/EndlessMethod:
  Enabled: true
Style/EnvHome:
  Enabled: true
Style/ExactRegexpMatch:
  Enabled: true
Style/FetchEnvVar:
  Enabled: true
Style/FileEmpty:
  Enabled: true
Style/FileNull:
  Enabled: true
Style/FileRead:
  Enabled: true
Style/FileTouch:
  Enabled: true
Style/FileWrite:
  Enabled: true
Style/FrozenStringLiteralComment:
  Enabled: true
Style/HashConversion:
  Enabled: true
Style/HashExcept:
  Enabled: true
Style/HashFetchChain:
  Enabled: true
Style/HashSlice:
  Enabled: true
Style/IfWithBooleanLiteralBranches:
  Enabled: true
Style/InPatternThen:
  Enabled: true
Style/ItAssignment:
  Enabled: true
Style/ItBlockParameter:
  Enabled: true
Style/KeywordArgumentsMerging:
  Enabled: true
Style/MagicCommentFormat:
  Enabled: true
Style/MapCompactWithConditionalBlock:
  Enabled: true
Style/MapIntoArray:
  Enabled: true
Style/MapToHash:
  Enabled: true
Style/MapToSet:
  Enabled: true
Style/MinMaxComparison:
  Enabled: true
Style/ModuleMemberExistenceCheck:
  Enabled: true
Style/MultilineBlockChain:
  Enabled: true
Style/MultilineInPatternThen:
  Enabled: true
Style/NegatedIfElseCondition:
  Enabled: true
Style/NegativeArrayIndex:
  Enabled: true
Style/NestedFileDirname:
  Enabled: true
Style/NilLambda:
  Enabled: true
Style/NumberedParameters:
  Enabled: true
Style/NumberedParametersLimit:
  Enabled: true
Style/NumericPredicate:
  Enabled: true
Style/ObjectThen:
  Enabled: true
Style/OpenStructUse:
  Enabled: true
Style/OperatorMethodCall:
  Enabled: true
Style/OptionalBooleanParameter:
  Enabled: true
Style/QuotedSymbols:
  Enabled: true
Style/RedundantArgument:
  Enabled: true
Style/RedundantArrayConstructor:
  Enabled: true
Style/RedundantArrayFlatten:
  Enabled: true
Style/RedundantConstantBase:
  Enabled: true
Style/RedundantCurrentDirectoryInPath:
  Enabled: true
Style/RedundantDoubleSplatHashBraces:
  Enabled: true
Style/RedundantEach:
  Enabled: true
Style/RedundantFilterChain:
  Enabled: true
Style/RedundantFormat:
  Enabled: true
Style/RedundantHeredocDelimiterQuotes:
  Enabled: true
Style/RedundantInitialize:
  Enabled: true
Style/RedundantInterpolationUnfreeze:
  Enabled: true
Style/RedundantLineContinuation:
  Enabled: true
Style/RedundantRegexpArgument:
  Enabled: true
Style/RedundantRegexpConstructor:
  Enabled: true
Style/RedundantSelfAssignmentBranch:
  Enabled: true
Style/RedundantStringEscape:
  Enabled: true
Style/ReturnNilInPredicateMethodDefinition:
  Enabled: true
Style/ReverseFind:
  Enabled: true
Style/SafeNavigation:
  Enabled: true
Style/SafeNavigationChainLength:
  Enabled: true
Style/SelectByRegexp:
  Enabled: true
Style/SendWithLiteralMethodName:
  Enabled: true
Style/SingleLineDoEndBlock:
  Enabled: true
Style/StringChars:
  Enabled: true
Style/StringConcatenation:
  Enabled: true
Style/StructInheritance:
  Enabled: true
Style/SuperArguments:
  Enabled: true
Style/SuperWithArgsParentheses:
  Enabled: true
Style/SwapValues:
  Enabled: true
Style/TernaryParentheses:
  Enabled: true
Style/YAMLFileRead:
  Enabled: true


#### DISABLED SECTION
Lint/ShadowedException: # Breaks "bundle exec rake rubocop" if enabled
  Enabled: false
Rails/CreateTableWithTimestamps: # Only works with ActiveRecord but we're using Sequel
  Enabled: false
Rails/DangerousColumnNames: # Disabled, in comparison to active_record we need to add the id column manually in sequel
  Enabled: false
Rails/DynamicFindBy: # Breaks Code
  Enabled: false
Rails/FindEach: # Breaks Code
  Enabled: false
Rails/I18nLocaleTexts: # We don't use locale texts
  Enabled: false
Rails/RedundantActiveRecordAllMethod: # As we use Sequel this breaks code as it matches Sequel functions
  Enabled: false
Sequel/SaveChanges: # Breaks Code
  Enabled: false
