require:
  - ./spec/linters/migration/add_constraint_name.rb
  - ./spec/linters/migration/include_string_size.rb
  - ./spec/linters/migration/require_primary_key.rb
  - ./spec/linters/match_requires_with_includes.rb

AllCops:
  TargetRubyVersion: 3.1
  Exclude:
    - errors/**/*
    - lib/diego/bbs/models/**/*
    - lib/locket/**/*
    - lib/logcache/v2/**/*
    - vendor/bundle/**/*

Bundler/DuplicatedGem:
  Enabled: false

Layout/ArgumentAlignment:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Layout/ParameterAlignment:
  Enabled: false

Layout/ClosingParenthesisIndentation:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  Enabled: false

Layout/MultilineArrayBraceLayout:
  Enabled: false

Layout/MultilineBlockLayout:
  Enabled: false

Layout/MultilineHashBraceLayout:
  Enabled: false

Layout/MultilineMethodCallBraceLayout:
  Enabled: false

Layout/MultilineMethodDefinitionBraceLayout:
  Enabled: false

Layout/MultilineOperationIndentation:
  Enabled: false

Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Lint/AmbiguousBlockAssociation:
  Enabled: false

Lint/AmbiguousRegexpLiteral:
  Enabled: false

Lint/SuppressedException:
  Enabled: false

Lint/ShadowedException:
  Enabled: false

Lint/ScriptPermission:
  Enabled: false

Lint/UnifiedInteger:
  Exclude:
    - db/migrations/**/*

Lint/RedundantCopDisableDirective:
  Exclude:
    - db/migrations/201[3-7]*

Lint/RedundantCopEnableDirective:
  Exclude:
    - db/migrations/20130806175100_support_30char_identifiers_for_oracle.rb

Lint/UnusedBlockArgument:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Lint/UriEscapeUnescape:
  Enabled: true

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - db/migrations/**/*
    - spec/**/*
    - lib/cloud_controller/config.rb
    - config/routes.rb
    - lib/tasks/db.rake
    - lib/tasks/jobs.rake

  Max: 50

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 12

Layout/LineLength:
  Max: 180

Metrics/MethodLength:
  Max: 60

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Migration/AddConstraintName:
  Include:
    - 'db/migrations/**/*'
  Exclude:
    # skip old migration files since we do not want to fix them after they are in the wild
    - !ruby/regexp /db/migrations/201([0-6]|70[1-6]).+\.rb$/
    - db/migrations/20221125134500_add_request_count_table.rb

Migration/IncludeStringSize:
  Include:
    - 'db/migrations/**/*'
  Exclude:
    # skip old migration files since we do not want to fix them after they are in the wild
    - !ruby/regexp /db/migrations/201([0-6]|70[1-6]|707[01]).+\.rb$/
    - db/migrations/20221125134500_add_request_count_table.rb

Migration/RequirePrimaryKey:
  Include:
    - 'db/migrations/**/*'
  Exclude:
    # skip old migration files since we do not want to fix them after they are in the wild
    - !ruby/regexp /db/migrations/201([0-7]|80[1-3]).+\.rb$/

Naming/FileName:
  Exclude:
    - Guardfile

Naming/HeredocDelimiterNaming:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  Enabled: false

Naming/MethodParameterName:
  # Parameter names may be equal to or greater than this value
  MinNameLength: 3
  AllowNamesEndingInNumbers: true
  # Whitelisted names that will not register an offense
  AllowedNames:
    - '_'
    - e
    - io
    - id
    - to
    - by
    - 'on'
    - in
    - at
    - ip
    - db
  # Blacklisted names that will register an offense
  ForbiddenNames: []

Naming/VariableNumber:
  Enabled: false

Style/Sample:
  Enabled: false

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/BlockDelimiters:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/Encoding:
  Exclude:
    - '**/*.pb.rb'

Style/ExpandPathArguments:
  Exclude:
    - 'db/migrations/20130911111938_encrypt_app_env_json.rb'
    - 'db/migrations/201805*'

Style/FloatDivision:
  Enabled: false

Style/FormatString:
  EnforcedStyle: sprintf

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/Next:
  Enabled: false

Style/NumericLiteralPrefix:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/RaiseArgs:
  EnforcedStyle: compact

Style/RedundantSelf:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/RescueStandardError:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/StructInheritance:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/TernaryParentheses:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/TrailingUnderscoreVariable:
  Enabled: false

Style/TrivialAccessors:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/HashEachMethods:
  Enabled: false

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: false

Style/SlicingWithRange:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Style/RedundantRegexpCharacterClass:
  Enabled: false

Style/RedundantRegexpEscape:
  Enabled: false

Lint/BinaryOperatorWithIdenticalOperands:
  Enabled: false

Lint/DuplicateElsifCondition:
  Enabled: true

Lint/DuplicateRescueException:
  Enabled: true

Lint/EmptyConditionalBody:
  Enabled: false

Lint/FloatComparison:
  Enabled: true

Lint/MissingSuper:
  Enabled: false

Lint/OutOfRangeRegexpRef:
  Enabled: true

Lint/SelfAssignment:
  Enabled: true

Lint/TopLevelReturnWithArgument:
  Enabled: true

Lint/UnreachableLoop:
  Enabled: true

Style/AccessorGrouping:
  Enabled: true

Style/ArrayCoercion:
  Enabled: true

Style/BisectedAttrAccessor:
  Enabled: true

Style/CaseLikeIf:
  Enabled: false

Style/ExplicitBlockArgument:
  Enabled: true

Style/GlobalStdStream:
  Enabled: true

Style/HashAsLastArrayItem:
  Enabled: true

Style/HashLikeCase:
  Enabled: true

Style/OptionalBooleanParameter:
  Enabled: false

Style/RedundantAssignment:
  Enabled: false

Style/RedundantFetchBlock:
  Enabled: true

Style/RedundantFileExtensionInRequire:
  Enabled: true

Style/SingleArgumentDig:
  Enabled: true

Style/StringConcatenation:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Lint/DuplicateRequire:
  Enabled: true

Lint/EmptyFile:
  Enabled: true

Lint/TrailingCommaInAttributeDeclaration:
  Enabled: true

Lint/UselessMethodDefinition:
  Enabled: false

Style/CombinableLoops:
  Enabled: false

Style/KeywordParametersOrder:
  Enabled: false

Style/RedundantSelfAssignment:
  Enabled: true

Style/SoleNestedConditional:
  Enabled: false

Layout/BeginEndAlignment:
  Enabled: true

Lint/ConstantDefinitionInBlock:
  Enabled: false

Lint/IdentityComparison:
  Enabled: true

Lint/UselessTimes:
  Enabled: true

Lint/HashCompareByIdentity:
  Enabled: true

Lint/RedundantSafeNavigation:
  Enabled: true

Style/ClassEqualityComparison:
  Enabled: true

Lint/DuplicateRegexpCharacterClassElement: # (new in 1.1)
  Enabled: true

Lint/EmptyBlock: # (new in 1.1)
  Enabled: false

Lint/ToEnumArguments: # (new in 1.1)
  Enabled: true

Lint/UnmodifiedReduceAccumulator: # (new in 1.1)
  Enabled: true

Style/ArgumentsForwarding: # (new in 1.1)
  Enabled: true

Style/DocumentDynamicEvalDefinition: # (new in 1.1)
  Enabled: true

Style/SwapValues: # (new in 1.1)
  Enabled: true

Lint/NoReturnInBeginEndBlocks: # (new in 1.2)
  Enabled: true

Style/CollectionCompact: # (new in 1.2)
  Enabled: false

Style/NegatedIfElseCondition: # (new in 1.2)
  Enabled: true

Lint/DuplicateBranch: # (new in 1.3)
  Enabled: true

Lint/EmptyClass: # (new in 1.3)
  Enabled: true

Style/NilLambda: # (new in 1.3)
  Enabled: true

Style/RedundantArgument: # (new in 1.4)
  Enabled: true

Layout/EmptyLineBetweenDefs:
  Enabled: true
  EmptyLineBetweenClassDefs: false

Lint/UnexpectedBlockArity: # (new in 1.5)
  Enabled: true

Layout/SpaceBeforeBrackets: # (new in 1.7)
  Enabled: false

Lint/AmbiguousAssignment: # (new in 1.7)
  Enabled: true

Style/HashExcept: # (new in 1.7)
  Enabled: true

Lint/DeprecatedConstants: # (new in 1.8)
  Enabled: true

Lint/LambdaWithoutLiteralBlock: # (new in 1.8)
  Enabled: true

Lint/RedundantDirGlobSort: # (new in 1.8)
  Enabled: true

Style/EndlessMethod: # (new in 1.8)
  Enabled: true

Lint/NumberedParameterAssignment: # (new in 1.9)
  Enabled: true

Lint/OrAssignmentToConstant: # (new in 1.9)
  Enabled: false

Lint/SymbolConversion: # (new in 1.9)
  Enabled: true

Lint/TripleQuotes: # (new in 1.9)
  Enabled: true

Style/IfWithBooleanLiteralBranches: # (new in 1.9)
  Enabled: true

Style/HashSyntax:
  EnforcedShorthandSyntax: never
