source 'https://rubygems.org'

gem 'addressable'
gem 'allowy', '>= 2.1.0'
gem 'clockwork', require: false
gem 'cloudfront-signer'
gem 'digest-xxhash'
gem 'em-http-request', '~> 1.1'
gem 'eventmachine', '~> 1.2.7'
gem 'fluent-logger'
gem 'googleapis-common-protos', '>= 1.3.12'
gem 'hashdiff'
gem 'honeycomb-beeline'
gem 'httpclient'
gem 'json-diff'
gem 'json_pure'
gem 'json-schema'
gem 'loggregator_emitter', '~> 5.0'
gem 'membrane', '~> 1.0'
gem 'mime-types', '~> 3.5'
gem 'mock_redis'
gem 'multi_json'
gem 'multipart-parser'
gem 'netaddr', '>= 2.0.4'
gem 'net-ssh'
gem 'newrelic_rpm'
gem 'nokogiri', '>=1.10.5'
gem 'oj'
gem 'openssl', '>= 3.2'
gem 'palm_civet'
gem 'prometheus-client'
gem 'public_suffix'
gem 'puma'
gem 'rake'
gem 'redis'
gem 'retryable'
gem 'rfc822'
gem 'rubyzip', '>= 1.3.0'
gem 'sequel', '~> 5.79'
gem 'sequel_pg', require: 'sequel'
gem 'sinatra', '~> 3.2'
gem 'sinatra-contrib'
gem 'sshkey'
gem 'statsd-ruby', '~> 1.5.0'
gem 'steno'
gem 'talentbox-delayed_job_sequel', '~> 4.3.0'
gem 'thin'
gem 'unf'
gem 'vmstat', '~> 2.3'
gem 'yajl-ruby'

# Rails Components
gem 'actionpack', '~> 7.1.0'
gem 'actionview', '~> 7.1.0'
gem 'activemodel', '~> 7.1.0'
gem 'railties', '~> 7.1.0'

gem 'azure-storage-blob', git: 'https://github.com/sethboyles/azure-storage-ruby.git', branch: 'x-ms-blob-content-type-fix-1.1'

gem 'fog-aliyun'
gem 'fog-aws'
gem 'fog-azure-rm', git: 'https://github.com/fog/fog-azure-rm.git', branch: 'fog-arm-cf'
gem 'fog-core', '~> 2.1.2'
gem 'fog-google', '~> 1.24.1'
gem 'fog-local'
gem 'fog-openstack'

gem 'cf-uaa-lib', '~> 4.0.4'
gem 'vcap-concurrency', git: 'https://github.com/cloudfoundry/vcap-concurrency.git', ref: '2a5b0179'

group :db do
  gem 'mysql2', '~> 0.5.6'
  gem 'pg'
end

group :operations do
  gem 'pry-byebug'
end

group :test do
  gem 'codeclimate-test-reporter', '>= 1.0.8', require: false
  gem 'machinist', '~> 1.0.6'
  gem 'parallel_tests'
  gem 'rack-test'
  gem 'rspec', '~> 3.13.0'
  gem 'rspec_api_documentation', '>= 6.1.0'
  gem 'rspec-collection_matchers'
  gem 'rspec-instafail'
  gem 'rspec-its'
  gem 'rspec-rails', '~> 6.1.2'
  gem 'rspec-wait'
  gem 'rubocop', '~> 1.63.4'
  gem 'rubocop-rails', '~> 2.24'
  gem 'rubocop-rspec', '~> 2.26'
  gem 'rubocop-sequel', '~> 0.3.4'
  gem 'timecop'
  gem 'webmock', '> 2.3.1'
end

group :development do
  gem 'byebug'
  gem 'debug', '~> 1.9'
  gem 'listen'
  gem 'roodi'
  gem 'solargraph'
  gem 'spork', git: 'https://github.com/sporkrb/spork', ref: '224df49' # '~> 1.0rc'
  gem 'spring'
  gem 'spring-commands-rspec'
end
