# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: actions.proto

require 'google/protobuf'

require 'environment_variables_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "diego.bbs.models.Action" do
    optional :download_action, :message, 1, "diego.bbs.models.DownloadAction"
    optional :upload_action, :message, 2, "diego.bbs.models.UploadAction"
    optional :run_action, :message, 3, "diego.bbs.models.RunAction"
    optional :timeout_action, :message, 4, "diego.bbs.models.TimeoutAction"
    optional :emit_progress_action, :message, 5, "diego.bbs.models.EmitProgressAction"
    optional :try_action, :message, 6, "diego.bbs.models.TryAction"
    optional :parallel_action, :message, 7, "diego.bbs.models.ParallelAction"
    optional :serial_action, :message, 8, "diego.bbs.models.SerialAction"
    optional :codependent_action, :message, 9, "diego.bbs.models.CodependentAction"
  end
  add_message "diego.bbs.models.DownloadAction" do
    optional :artifact, :string, 1
    optional :from, :string, 2
    optional :to, :string, 3
    optional :cache_key, :string, 4
    optional :log_source, :string, 5
    optional :user, :string, 6
    optional :checksum_algorithm, :string, 7
    optional :checksum_value, :string, 8
  end
  add_message "diego.bbs.models.UploadAction" do
    optional :artifact, :string, 1
    optional :from, :string, 2
    optional :to, :string, 3
    optional :log_source, :string, 4
    optional :user, :string, 5
  end
  add_message "diego.bbs.models.RunAction" do
    optional :path, :string, 1
    repeated :args, :string, 2
    optional :dir, :string, 3
    repeated :env, :message, 4, "diego.bbs.models.EnvironmentVariable"
    optional :resource_limits, :message, 5, "diego.bbs.models.ResourceLimits"
    optional :user, :string, 6
    optional :log_source, :string, 7
    optional :suppress_log_output, :bool, 8
  end
  add_message "diego.bbs.models.TimeoutAction" do
    optional :action, :message, 1, "diego.bbs.models.Action"
    optional :deprecated_timeout_ns, :int64, 2
    optional :log_source, :string, 3
    optional :timeout_ms, :int64, 4
  end
  add_message "diego.bbs.models.EmitProgressAction" do
    optional :action, :message, 1, "diego.bbs.models.Action"
    optional :start_message, :string, 2
    optional :success_message, :string, 3
    optional :failure_message_prefix, :string, 4
    optional :log_source, :string, 5
  end
  add_message "diego.bbs.models.TryAction" do
    optional :action, :message, 1, "diego.bbs.models.Action"
    optional :log_source, :string, 2
  end
  add_message "diego.bbs.models.ParallelAction" do
    repeated :actions, :message, 1, "diego.bbs.models.Action"
    optional :log_source, :string, 2
  end
  add_message "diego.bbs.models.SerialAction" do
    repeated :actions, :message, 1, "diego.bbs.models.Action"
    optional :log_source, :string, 2
  end
  add_message "diego.bbs.models.CodependentAction" do
    repeated :actions, :message, 1, "diego.bbs.models.Action"
    optional :log_source, :string, 2
  end
  add_message "diego.bbs.models.ResourceLimits" do
    oneof :optional_nofile do
      optional :nofile, :uint64, 1
    end
    oneof :optional_nproc do
      optional :nproc, :uint64, 2
    end
  end
end

module Diego
  module Bbs
    module Models
      Action = Google::Protobuf::DescriptorPool.generated_pool.lookup("diego.bbs.models.Action").msgclass
      DownloadAction = Google::Protobuf::DescriptorPool.generated_pool.lookup("diego.bbs.models.DownloadAction").msgclass
      UploadAction = Google::Protobuf::DescriptorPool.generated_pool.lookup("diego.bbs.models.UploadAction").msgclass
      RunAction = Google::Protobuf::DescriptorPool.generated_pool.lookup("diego.bbs.models.RunAction").msgclass
      TimeoutAction = Google::Protobuf::DescriptorPool.generated_pool.lookup("diego.bbs.models.TimeoutAction").msgclass
      EmitProgressAction = Google::Protobuf::DescriptorPool.generated_pool.lookup("diego.bbs.models.EmitProgressAction").msgclass
      TryAction = Google::Protobuf::DescriptorPool.generated_pool.lookup("diego.bbs.models.TryAction").msgclass
      ParallelAction = Google::Protobuf::DescriptorPool.generated_pool.lookup("diego.bbs.models.ParallelAction").msgclass
      SerialAction = Google::Protobuf::DescriptorPool.generated_pool.lookup("diego.bbs.models.SerialAction").msgclass
      CodependentAction = Google::Protobuf::DescriptorPool.generated_pool.lookup("diego.bbs.models.CodependentAction").msgclass
      ResourceLimits = Google::Protobuf::DescriptorPool.generated_pool.lookup("diego.bbs.models.ResourceLimits").msgclass
    end
  end
end
