# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: actual_lrp.proto

require 'google/protobuf'

require 'modification_tag_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("actual_lrp.proto", :syntax => :proto3) do
    add_message "diego.bbs.models.ActualLRPGroup" do
      optional :instance, :message, 1, "diego.bbs.models.ActualLRP"
      optional :evacuating, :message, 2, "diego.bbs.models.ActualLRP"
    end
    add_message "diego.bbs.models.PortMapping" do
      optional :container_port, :uint32, 1
      optional :host_port, :uint32, 2
      optional :container_tls_proxy_port, :uint32, 3
      optional :host_tls_proxy_port, :uint32, 4
    end
    add_message "diego.bbs.models.ActualLRPKey" do
      optional :process_guid, :string, 1
      optional :index, :int32, 2
      optional :domain, :string, 3
    end
    add_message "diego.bbs.models.ActualLRPInstanceKey" do
      optional :instance_guid, :string, 1
      optional :cell_id, :string, 2
    end
    add_message "diego.bbs.models.ActualLRPNetInfo" do
      optional :address, :string, 1
      repeated :ports, :message, 2, "diego.bbs.models.PortMapping"
      optional :instance_address, :string, 3
      optional :preferred_address, :enum, 4, "diego.bbs.models.ActualLRPNetInfo.PreferredAddress"
    end
    add_enum "diego.bbs.models.ActualLRPNetInfo.PreferredAddress" do
      value :UNKNOWN, 0
      value :INSTANCE, 1
      value :HOST, 2
    end
    add_message "diego.bbs.models.ActualLRP" do
      optional :actual_lrp_key, :message, 1, "diego.bbs.models.ActualLRPKey"
      optional :actual_lrp_instance_key, :message, 2, "diego.bbs.models.ActualLRPInstanceKey"
      optional :actual_lrp_net_info, :message, 3, "diego.bbs.models.ActualLRPNetInfo"
      optional :crash_count, :int32, 4
      optional :crash_reason, :string, 5
      optional :state, :string, 6
      optional :placement_error, :string, 7
      optional :since, :int64, 8
      optional :modification_tag, :message, 9, "diego.bbs.models.ModificationTag"
      optional :presence, :enum, 10, "diego.bbs.models.ActualLRP.Presence"
    end
    add_enum "diego.bbs.models.ActualLRP.Presence" do
      value :ORDINARY, 0
      value :EVACUATING, 1
      value :SUSPECT, 2
    end
  end
end

module Diego
  module Bbs
    module Models
      ActualLRPGroup = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("diego.bbs.models.ActualLRPGroup").msgclass
      PortMapping = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("diego.bbs.models.PortMapping").msgclass
      ActualLRPKey = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("diego.bbs.models.ActualLRPKey").msgclass
      ActualLRPInstanceKey = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("diego.bbs.models.ActualLRPInstanceKey").msgclass
      ActualLRPNetInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("diego.bbs.models.ActualLRPNetInfo").msgclass
      ActualLRPNetInfo::PreferredAddress = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("diego.bbs.models.ActualLRPNetInfo.PreferredAddress").enummodule
      ActualLRP = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("diego.bbs.models.ActualLRP").msgclass
      ActualLRP::Presence = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("diego.bbs.models.ActualLRP.Presence").enummodule
    end
  end
end
