# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: actual_lrp_requests.proto

require 'google/protobuf'

require 'actual_lrp_pb'
require 'error_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("actual_lrp_requests.proto", :syntax => :proto3) do
    add_message "diego.bbs.models.ActualLRPLifecycleResponse" do
      optional :error, :message, 1, "diego.bbs.models.Error"
    end
    add_message "diego.bbs.models.ActualLRPGroupsResponse" do
      optional :error, :message, 1, "diego.bbs.models.Error"
      repeated :actual_lrp_groups, :message, 2, "diego.bbs.models.ActualLRPGroup"
    end
    add_message "diego.bbs.models.ActualLRPGroupResponse" do
      optional :error, :message, 1, "diego.bbs.models.Error"
      optional :actual_lrp_group, :message, 2, "diego.bbs.models.ActualLRPGroup"
    end
    add_message "diego.bbs.models.ActualLRPGroupsRequest" do
      optional :domain, :string, 1
      optional :cell_id, :string, 2
    end
    add_message "diego.bbs.models.ActualLRPGroupsByProcessGuidRequest" do
      optional :process_guid, :string, 1
    end
    add_message "diego.bbs.models.ActualLRPGroupByProcessGuidAndIndexRequest" do
      optional :process_guid, :string, 1
      optional :index, :int32, 2
    end
    add_message "diego.bbs.models.ClaimActualLRPRequest" do
      optional :process_guid, :string, 1
      optional :index, :int32, 2
      optional :actual_lrp_instance_key, :message, 3, "diego.bbs.models.ActualLRPInstanceKey"
    end
    add_message "diego.bbs.models.StartActualLRPRequest" do
      optional :actual_lrp_key, :message, 1, "diego.bbs.models.ActualLRPKey"
      optional :actual_lrp_instance_key, :message, 2, "diego.bbs.models.ActualLRPInstanceKey"
      optional :actual_lrp_net_info, :message, 3, "diego.bbs.models.ActualLRPNetInfo"
    end
    add_message "diego.bbs.models.CrashActualLRPRequest" do
      optional :actual_lrp_key, :message, 1, "diego.bbs.models.ActualLRPKey"
      optional :actual_lrp_instance_key, :message, 2, "diego.bbs.models.ActualLRPInstanceKey"
      optional :error_message, :string, 3
    end
    add_message "diego.bbs.models.FailActualLRPRequest" do
      optional :actual_lrp_key, :message, 1, "diego.bbs.models.ActualLRPKey"
      optional :error_message, :string, 2
    end
    add_message "diego.bbs.models.RetireActualLRPRequest" do
      optional :actual_lrp_key, :message, 1, "diego.bbs.models.ActualLRPKey"
    end
    add_message "diego.bbs.models.RemoveActualLRPRequest" do
      optional :process_guid, :string, 1
      optional :index, :int32, 2
      optional :actual_lrp_instance_key, :message, 3, "diego.bbs.models.ActualLRPInstanceKey"
    end
    add_message "diego.bbs.models.ActualLRPsResponse" do
      optional :error, :message, 1, "diego.bbs.models.Error"
      repeated :actual_lrps, :message, 2, "diego.bbs.models.ActualLRP"
    end
    add_message "diego.bbs.models.ActualLRPsRequest" do
      optional :domain, :string, 1
      optional :cell_id, :string, 2
      optional :process_guid, :string, 3
      oneof :optional_index do
        optional :index, :int32, 4
      end
    end
  end
end

module Diego
  module Bbs
    module Models
      ActualLRPLifecycleResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("diego.bbs.models.ActualLRPLifecycleResponse").msgclass
      ActualLRPGroupsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("diego.bbs.models.ActualLRPGroupsResponse").msgclass
      ActualLRPGroupResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("diego.bbs.models.ActualLRPGroupResponse").msgclass
      ActualLRPGroupsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("diego.bbs.models.ActualLRPGroupsRequest").msgclass
      ActualLRPGroupsByProcessGuidRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("diego.bbs.models.ActualLRPGroupsByProcessGuidRequest").msgclass
      ActualLRPGroupByProcessGuidAndIndexRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("diego.bbs.models.ActualLRPGroupByProcessGuidAndIndexRequest").msgclass
      ClaimActualLRPRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("diego.bbs.models.ClaimActualLRPRequest").msgclass
      StartActualLRPRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("diego.bbs.models.StartActualLRPRequest").msgclass
      CrashActualLRPRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("diego.bbs.models.CrashActualLRPRequest").msgclass
      FailActualLRPRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("diego.bbs.models.FailActualLRPRequest").msgclass
      RetireActualLRPRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("diego.bbs.models.RetireActualLRPRequest").msgclass
      RemoveActualLRPRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("diego.bbs.models.RemoveActualLRPRequest").msgclass
      ActualLRPsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("diego.bbs.models.ActualLRPsResponse").msgclass
      ActualLRPsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("diego.bbs.models.ActualLRPsRequest").msgclass
    end
  end
end
