# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cells.proto

require 'google/protobuf'

require 'error_pb'


descriptor_data = "\n\x0b\x63\x65lls.proto\x12\x10\x64iego.bbs.models\x1a\x0b\x65rror.proto\"F\n\x0c\x43\x65llCapacity\x12\x11\n\tmemory_mb\x18\x01 \x01(\x05\x12\x0f\n\x07\x64isk_mb\x18\x02 \x01(\x05\x12\x12\n\ncontainers\x18\x03 \x01(\x05\"\xf4\x01\n\x0c\x43\x65llPresence\x12\x0f\n\x07\x63\x65ll_id\x18\x01 \x01(\t\x12\x13\n\x0brep_address\x18\x02 \x01(\t\x12\x0c\n\x04zone\x18\x03 \x01(\t\x12\x30\n\x08\x63\x61pacity\x18\x04 \x01(\x0b\x32\x1e.diego.bbs.models.CellCapacity\x12\x34\n\x10rootfs_providers\x18\x05 \x03(\x0b\x32\x1a.diego.bbs.models.Provider\x12\x16\n\x0eplacement_tags\x18\x06 \x03(\t\x12\x1f\n\x17optional_placement_tags\x18\x07 \x03(\t\x12\x0f\n\x07rep_url\x18\x08 \x01(\t\",\n\x08Provider\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x12\n\nproperties\x18\x02 \x03(\t\"f\n\rCellsResponse\x12&\n\x05\x65rror\x18\x01 \x01(\x0b\x32\x17.diego.bbs.models.Error\x12-\n\x05\x63\x65lls\x18\x02 \x03(\x0b\x32\x1e.diego.bbs.models.CellPresenceb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Diego
  module Bbs
    module Models
      CellCapacity = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("diego.bbs.models.CellCapacity").msgclass
      CellPresence = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("diego.bbs.models.CellPresence").msgclass
      Provider = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("diego.bbs.models.Provider").msgclass
      CellsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("diego.bbs.models.CellsResponse").msgclass
    end
  end
end
