# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: desired_lrp_requests.proto

require 'google/protobuf'

require 'desired_lrp_pb'
require 'error_pb'


descriptor_data = "\n\x1a\x64\x65sired_lrp_requests.proto\x12\x10\x64iego.bbs.models\x1a\x11\x64\x65sired_lrp.proto\x1a\x0b\x65rror.proto\"E\n\x1b\x44\x65siredLRPLifecycleResponse\x12&\n\x05\x65rror\x18\x01 \x01(\x0b\x32\x17.diego.bbs.models.Error\"q\n\x13\x44\x65siredLRPsResponse\x12&\n\x05\x65rror\x18\x01 \x01(\x0b\x32\x17.diego.bbs.models.Error\x12\x32\n\x0c\x64\x65sired_lrps\x18\x02 \x03(\x0b\x32\x1c.diego.bbs.models.DesiredLRP\"N\n\x12\x44\x65siredLRPsRequest\x12\x0e\n\x06\x64omain\x18\x01 \x01(\t\x12\x15\n\rprocess_guids\x18\x02 \x03(\t\x12\x11\n\tapp_guids\x18\x03 \x03(\t\"o\n\x12\x44\x65siredLRPResponse\x12&\n\x05\x65rror\x18\x01 \x01(\x0b\x32\x17.diego.bbs.models.Error\x12\x31\n\x0b\x64\x65sired_lrp\x18\x02 \x01(\x0b\x32\x1c.diego.bbs.models.DesiredLRP\"\x9d\x01\n!DesiredLRPSchedulingInfosResponse\x12&\n\x05\x65rror\x18\x01 \x01(\x0b\x32\x17.diego.bbs.models.Error\x12P\n\x1c\x64\x65sired_lrp_scheduling_infos\x18\x02 \x03(\x0b\x32*.diego.bbs.models.DesiredLRPSchedulingInfo\"\xa8\x01\n-DesiredLRPSchedulingInfoByProcessGuidResponse\x12&\n\x05\x65rror\x18\x01 \x01(\x0b\x32\x17.diego.bbs.models.Error\x12O\n\x1b\x64\x65sired_lrp_scheduling_info\x18\x02 \x01(\x0b\x32*.diego.bbs.models.DesiredLRPSchedulingInfo\"6\n\x1e\x44\x65siredLRPByProcessGuidRequest\x12\x14\n\x0cprocess_guid\x18\x01 \x01(\t\"E\n\x10\x44\x65sireLRPRequest\x12\x31\n\x0b\x64\x65sired_lrp\x18\x01 \x01(\x0b\x32\x1c.diego.bbs.models.DesiredLRP\"c\n\x17UpdateDesiredLRPRequest\x12\x14\n\x0cprocess_guid\x18\x01 \x01(\t\x12\x32\n\x06update\x18\x02 \x01(\x0b\x32\".diego.bbs.models.DesiredLRPUpdate\"/\n\x17RemoveDesiredLRPRequest\x12\x14\n\x0cprocess_guid\x18\x01 \x01(\tb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Diego
  module Bbs
    module Models
      DesiredLRPLifecycleResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("diego.bbs.models.DesiredLRPLifecycleResponse").msgclass
      DesiredLRPsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("diego.bbs.models.DesiredLRPsResponse").msgclass
      DesiredLRPsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("diego.bbs.models.DesiredLRPsRequest").msgclass
      DesiredLRPResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("diego.bbs.models.DesiredLRPResponse").msgclass
      DesiredLRPSchedulingInfosResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("diego.bbs.models.DesiredLRPSchedulingInfosResponse").msgclass
      DesiredLRPSchedulingInfoByProcessGuidResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("diego.bbs.models.DesiredLRPSchedulingInfoByProcessGuidResponse").msgclass
      DesiredLRPByProcessGuidRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("diego.bbs.models.DesiredLRPByProcessGuidRequest").msgclass
      DesireLRPRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("diego.bbs.models.DesireLRPRequest").msgclass
      UpdateDesiredLRPRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("diego.bbs.models.UpdateDesiredLRPRequest").msgclass
      RemoveDesiredLRPRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("diego.bbs.models.RemoveDesiredLRPRequest").msgclass
    end
  end
end
