# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: domain.proto

require 'google/protobuf'

require 'error_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("domain.proto", :syntax => :proto3) do
    add_message "diego.bbs.models.DomainsResponse" do
      optional :error, :message, 1, "diego.bbs.models.Error"
      repeated :domains, :string, 2
    end
    add_message "diego.bbs.models.UpsertDomainResponse" do
      optional :error, :message, 1, "diego.bbs.models.Error"
    end
    add_message "diego.bbs.models.UpsertDomainRequest" do
      optional :domain, :string, 1
      optional :ttl, :uint32, 2
    end
  end
end

module Diego
  module Bbs
    module Models
      DomainsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("diego.bbs.models.DomainsResponse").msgclass
      UpsertDomainResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("diego.bbs.models.UpsertDomainResponse").msgclass
      UpsertDomainRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("diego.bbs.models.UpsertDomainRequest").msgclass
    end
  end
end
