# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: environment_variables.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("environment_variables.proto", :syntax => :proto3) do
    add_message "diego.bbs.models.EnvironmentVariable" do
      optional :name, :string, 1
      optional :value, :string, 2
    end
  end
end

module Diego
  module Bbs
    module Models
      EnvironmentVariable = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("diego.bbs.models.EnvironmentVariable").msgclass
    end
  end
end
