# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: error.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("error.proto", :syntax => :proto3) do
    add_message "diego.bbs.models.Error" do
      optional :type, :enum, 1, "diego.bbs.models.Error.Type"
      optional :message, :string, 2
    end
    add_enum "diego.bbs.models.Error.Type" do
      value :UnknownError, 0
      value :InvalidRecord, 3
      value :InvalidRequest, 4
      value :InvalidResponse, 5
      value :InvalidProtobufMessage, 6
      value :InvalidJSON, 7
      value :FailedToOpenEnvelope, 8
      value :InvalidStateTransition, 9
      value :ResourceConflict, 11
      value :ResourceExists, 12
      value :ResourceNotFound, 13
      value :RouterError, 14
      value :ActualLRPCannotBeClaimed, 15
      value :ActualLRPCannotBeStarted, 16
      value :ActualLRPCannotBeCrashed, 17
      value :ActualLRPCannotBeFailed, 18
      value :ActualLRPCannotBeRemoved, 19
      value :ActualLRPCannotBeUnclaimed, 21
      value :RunningOnDifferentCell, 24
      value :GUIDGeneration, 26
      value :Deserialize, 27
      value :Deadlock, 28
      value :Unrecoverable, 29
      value :LockCollision, 30
      value :Timeout, 31
    end
  end
end

module Diego
  module Bbs
    module Models
      Error = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("diego.bbs.models.Error").msgclass
      Error::Type = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("diego.bbs.models.Error.Type").enummodule
    end
  end
end
