# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: files.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "diego.bbs.models.Files" do
    optional :name, :string, 1
    optional :value, :string, 2
  end
end

module Diego
  module Bbs
    module Models
      Files = Google::Protobuf::DescriptorPool.generated_pool.lookup("diego.bbs.models.Files").msgclass
    end
  end
end
