# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: file.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "diego.bbs.models.File" do
    optional :path, :string, 1
    optional :content, :string, 2
  end
end

module Diego
  module Bbs
    module Models
      File = Google::Protobuf::DescriptorPool.generated_pool.lookup("diego.bbs.models.File").msgclass
    end
  end
end
