# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: log_rate_limit.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "diego.bbs.models.LogRateLimit" do
    optional :bytes_per_second, :int64, 1
  end
end

module Diego
  module Bbs
    module Models
      LogRateLimit = Google::Protobuf::DescriptorPool.generated_pool.lookup("diego.bbs.models.LogRateLimit").msgclass
    end
  end
end
