# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: network.proto

require 'google/protobuf'


descriptor_data = "\n\rnetwork.proto\x12\x10\x64iego.bbs.models\"{\n\x07Network\x12=\n\nproperties\x18\x01 \x03(\x0b\x32).diego.bbs.models.Network.PropertiesEntry\x1a\x31\n\x0fPropertiesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x62\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Diego
  module Bbs
    module Models
      Network = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("diego.bbs.models.Network").msgclass
    end
  end
end
