# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ping.proto

require 'google/protobuf'


descriptor_data = "\n\nping.proto\x12\x10\x64iego.bbs.models\"!\n\x0cPingResponse\x12\x11\n\tavailable\x18\x01 \x01(\x08\x62\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Diego
  module Bbs
    module Models
      PingResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("diego.bbs.models.PingResponse").msgclass
    end
  end
end
