# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: security_group.proto

require 'google/protobuf'


descriptor_data = "\n\x14security_group.proto\x12\x10\x64iego.bbs.models\"\'\n\tPortRange\x12\r\n\x05start\x18\x01 \x01(\r\x12\x0b\n\x03\x65nd\x18\x02 \x01(\r\"&\n\x08ICMPInfo\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12\x0c\n\x04\x63ode\x18\x02 \x01(\x05\"\xd0\x01\n\x11SecurityGroupRule\x12\x10\n\x08protocol\x18\x01 \x01(\t\x12\x14\n\x0c\x64\x65stinations\x18\x02 \x03(\t\x12\x11\n\x05ports\x18\x03 \x03(\rB\x02\x10\x00\x12/\n\nport_range\x18\x04 \x01(\x0b\x32\x1b.diego.bbs.models.PortRange\x12-\n\ticmp_info\x18\x05 \x01(\x0b\x32\x1a.diego.bbs.models.ICMPInfo\x12\x0b\n\x03log\x18\x06 \x01(\x08\x12\x13\n\x0b\x61nnotations\x18\x07 \x03(\tb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Diego
  module Bbs
    module Models
      PortRange = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("diego.bbs.models.PortRange").msgclass
      ICMPInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("diego.bbs.models.ICMPInfo").msgclass
      SecurityGroupRule = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("diego.bbs.models.SecurityGroupRule").msgclass
    end
  end
end
