# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: task_requests.proto

require 'google/protobuf'

require 'task_pb'
require 'error_pb'


descriptor_data = "\n\x13task_requests.proto\x12\x10\x64iego.bbs.models\x1a\ntask.proto\x1a\x0b\x65rror.proto\"?\n\x15TaskLifecycleResponse\x12&\n\x05\x65rror\x18\x01 \x01(\x0b\x32\x17.diego.bbs.models.Error\"q\n\x11\x44\x65sireTaskRequest\x12\x39\n\x0ftask_definition\x18\x01 \x01(\x0b\x32 .diego.bbs.models.TaskDefinition\x12\x11\n\ttask_guid\x18\x02 \x01(\t\x12\x0e\n\x06\x64omain\x18\x03 \x01(\t\"6\n\x10StartTaskRequest\x12\x11\n\ttask_guid\x18\x01 \x01(\t\x12\x0f\n\x07\x63\x65ll_id\x18\x02 \x01(\t\"Q\n\x11StartTaskResponse\x12&\n\x05\x65rror\x18\x01 \x01(\x0b\x32\x17.diego.bbs.models.Error\x12\x14\n\x0cshould_start\x18\x02 \x01(\x08\"@\n\x0f\x46\x61ilTaskRequest\x12\x11\n\ttask_guid\x18\x01 \x01(\t\x12\x16\n\x0e\x66\x61ilure_reason\x18\x02 \x01(\t:\x02\x18\x01\"@\n\x11RejectTaskRequest\x12\x11\n\ttask_guid\x18\x01 \x01(\t\x12\x18\n\x10rejection_reason\x18\x02 \x01(\t\"$\n\x0fTaskGuidRequest\x12\x11\n\ttask_guid\x18\x01 \x01(\t\"q\n\x13\x43ompleteTaskRequest\x12\x11\n\ttask_guid\x18\x01 \x01(\t\x12\x0f\n\x07\x63\x65ll_id\x18\x02 \x01(\t\x12\x0e\n\x06\x66\x61iled\x18\x03 \x01(\x08\x12\x16\n\x0e\x66\x61ilure_reason\x18\x04 \x01(\t\x12\x0e\n\x06result\x18\x05 \x01(\t\"\x89\x01\n\x14TaskCallbackResponse\x12\x11\n\ttask_guid\x18\x01 \x01(\t\x12\x0e\n\x06\x66\x61iled\x18\x02 \x01(\x08\x12\x16\n\x0e\x66\x61ilure_reason\x18\x03 \x01(\t\x12\x0e\n\x06result\x18\x04 \x01(\t\x12\x12\n\nannotation\x18\x05 \x01(\t\x12\x12\n\ncreated_at\x18\x06 \x01(\x03\"/\n\x0cTasksRequest\x12\x0e\n\x06\x64omain\x18\x01 \x01(\t\x12\x0f\n\x07\x63\x65ll_id\x18\x02 \x01(\t\"^\n\rTasksResponse\x12&\n\x05\x65rror\x18\x01 \x01(\x0b\x32\x17.diego.bbs.models.Error\x12%\n\x05tasks\x18\x02 \x03(\x0b\x32\x16.diego.bbs.models.Task\"&\n\x11TaskByGuidRequest\x12\x11\n\ttask_guid\x18\x01 \x01(\t\"\\\n\x0cTaskResponse\x12&\n\x05\x65rror\x18\x01 \x01(\x0b\x32\x17.diego.bbs.models.Error\x12$\n\x04task\x18\x02 \x01(\x0b\x32\x16.diego.bbs.models.Taskb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Diego
  module Bbs
    module Models
      TaskLifecycleResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("diego.bbs.models.TaskLifecycleResponse").msgclass
      DesireTaskRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("diego.bbs.models.DesireTaskRequest").msgclass
      StartTaskRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("diego.bbs.models.StartTaskRequest").msgclass
      StartTaskResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("diego.bbs.models.StartTaskResponse").msgclass
      FailTaskRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("diego.bbs.models.FailTaskRequest").msgclass
      RejectTaskRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("diego.bbs.models.RejectTaskRequest").msgclass
      TaskGuidRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("diego.bbs.models.TaskGuidRequest").msgclass
      CompleteTaskRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("diego.bbs.models.CompleteTaskRequest").msgclass
      TaskCallbackResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("diego.bbs.models.TaskCallbackResponse").msgclass
      TasksRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("diego.bbs.models.TasksRequest").msgclass
      TasksResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("diego.bbs.models.TasksResponse").msgclass
      TaskByGuidRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("diego.bbs.models.TaskByGuidRequest").msgclass
      TaskResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("diego.bbs.models.TaskResponse").msgclass
    end
  end
end
