# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: task_requests.proto

require 'google/protobuf'

require 'task_pb'
require 'error_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("task_requests.proto", :syntax => :proto3) do
    add_message "diego.bbs.models.TaskLifecycleResponse" do
      optional :error, :message, 1, "diego.bbs.models.Error"
    end
    add_message "diego.bbs.models.DesireTaskRequest" do
      optional :task_definition, :message, 1, "diego.bbs.models.TaskDefinition"
      optional :task_guid, :string, 2
      optional :domain, :string, 3
    end
    add_message "diego.bbs.models.StartTaskRequest" do
      optional :task_guid, :string, 1
      optional :cell_id, :string, 2
    end
    add_message "diego.bbs.models.StartTaskResponse" do
      optional :error, :message, 1, "diego.bbs.models.Error"
      optional :should_start, :bool, 2
    end
    add_message "diego.bbs.models.FailTaskRequest" do
      optional :task_guid, :string, 1
      optional :failure_reason, :string, 2
    end
    add_message "diego.bbs.models.RejectTaskRequest" do
      optional :task_guid, :string, 1
      optional :rejection_reason, :string, 2
    end
    add_message "diego.bbs.models.TaskGuidRequest" do
      optional :task_guid, :string, 1
    end
    add_message "diego.bbs.models.CompleteTaskRequest" do
      optional :task_guid, :string, 1
      optional :cell_id, :string, 2
      optional :failed, :bool, 3
      optional :failure_reason, :string, 4
      optional :result, :string, 5
    end
    add_message "diego.bbs.models.TaskCallbackResponse" do
      optional :task_guid, :string, 1
      optional :failed, :bool, 2
      optional :failure_reason, :string, 3
      optional :result, :string, 4
      optional :annotation, :string, 5
      optional :created_at, :int64, 6
    end
    add_message "diego.bbs.models.TasksRequest" do
      optional :domain, :string, 1
      optional :cell_id, :string, 2
    end
    add_message "diego.bbs.models.TasksResponse" do
      optional :error, :message, 1, "diego.bbs.models.Error"
      repeated :tasks, :message, 2, "diego.bbs.models.Task"
    end
    add_message "diego.bbs.models.TaskByGuidRequest" do
      optional :task_guid, :string, 1
    end
    add_message "diego.bbs.models.TaskResponse" do
      optional :error, :message, 1, "diego.bbs.models.Error"
      optional :task, :message, 2, "diego.bbs.models.Task"
    end
  end
end

module Diego
  module Bbs
    module Models
      TaskLifecycleResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("diego.bbs.models.TaskLifecycleResponse").msgclass
      DesireTaskRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("diego.bbs.models.DesireTaskRequest").msgclass
      StartTaskRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("diego.bbs.models.StartTaskRequest").msgclass
      StartTaskResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("diego.bbs.models.StartTaskResponse").msgclass
      FailTaskRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("diego.bbs.models.FailTaskRequest").msgclass
      RejectTaskRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("diego.bbs.models.RejectTaskRequest").msgclass
      TaskGuidRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("diego.bbs.models.TaskGuidRequest").msgclass
      CompleteTaskRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("diego.bbs.models.CompleteTaskRequest").msgclass
      TaskCallbackResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("diego.bbs.models.TaskCallbackResponse").msgclass
      TasksRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("diego.bbs.models.TasksRequest").msgclass
      TasksResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("diego.bbs.models.TasksResponse").msgclass
      TaskByGuidRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("diego.bbs.models.TaskByGuidRequest").msgclass
      TaskResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("diego.bbs.models.TaskResponse").msgclass
    end
  end
end
