#!/usr/bin/env bash
#
# Render README.md (intro + Mermaid chart + table) from the CSV data file.
# Usage: render_retrigger_readme.sh <csv-path> > README.md
#
set -euo pipefail

CSV="${1:?usage: render_retrigger_readme.sh <csv-path>}"

months="$(awk -F, 'NR>1 {printf "%s\"%s\"", sep, $1; sep=", "}' "${CSV}")"
values="$(awk -F, 'NR>1 {printf "%s%s", sep, $4; sep=", "}' "${CSV}")"

cat <<EOF
# Unit Tests — monthly re-trigger rate (main)

How often the [\`Unit Tests\`](../../blob/main/.github/workflows/unit_tests.yml) workflow on \`main\`
was **re-triggered** to green, as a percentage of runs per month.

A run counts when its final \`run_attempt >= 2\` **and** it eventually succeeded — a proxy
for flakiness. Re-runs that still failed are real failures and are excluded.

> Auto-generated by \`.github/workflows/unit_test_flakiness_report.yml\`. Each run upserts
> the months still in the API into \`data/retrigger_rate.csv\`, preserving history past
> GitHub's ~400-day run retention. Do not edit this branch by hand.

\`\`\`mermaid
xychart-beta
    title "Unit Tests re-trigger rate on main (%)"
    x-axis [${months}]
    y-axis "Re-trigger %" 0 --> 100
    line [${values}]
\`\`\`

## Data

| Month | Runs | Re-triggered | Re-trigger % |
|-------|-----:|-------------:|-------------:|
EOF

awk -F, 'NR>1 {printf "| %s | %s | %s | %s%% |\n", $1, $2, $3, $4}' "${CSV}"
