#!/usr/bin/env bash
#
# Render README.md (intro + one Mermaid xychart-beta per DB engine + full table) from the
# duration CSV. Engines and versions are parsed from the job names (Test-<Engine> (<image>)),
# so new ones self-plot. Non-matrix jobs (e.g. Rubocop) appear in the table only.
# Usage: render_duration_readme.sh <csv-path> > README.md
#
set -euo pipefail

CSV="${1:?usage: render_duration_readme.sh <csv-path>}"

# Distinct months, ascending — the shared x-axis for every chart.
months_csv="$(awk -F, 'NR>1 {print $1}' "${CSV}" | sort -u | paste -sd, -)"
months_axis="$(printf '%s' "${months_csv}" | awk -F, '{for(i=1;i<=NF;i++) printf "%s\"%s\"", (i>1?", ":""), $i}')"
latest_month="$(awk -F, 'NR>1 {print $1}' "${CSV}" | sort -u | tail -1)"

# Distinct engines (Test-<Engine>), in first-seen-then-sorted order.
engines="$(awk -F, 'NR>1 && $2 ~ /^Test-[A-Za-z]+ \(/ {
             e=$2; sub(/^Test-/,"",e); sub(/ \(.*/,"",e); print e }' "${CSV}" | sort -u)"

cat <<EOF
# Unit Tests — monthly median job duration (main)

Median (p50) wall-clock duration of each [\`Unit Tests\`](../../blob/main/.github/workflows/unit_tests.yml)
job on \`main\`, per month, split by database engine. Only jobs that **succeeded** count — a
failed or timed-out job's duration is meaningless. Duration includes DB-service start-up but
not queue time; it is comparable across months.

> Auto-generated by \`.github/workflows/unit_test_duration_report.yml\`. Each run upserts the
> completed months still in the API into \`data/job_duration.csv\`, preserving history past
> GitHub's ~400-day run retention. Do not edit this branch by hand.
EOF

# One chart per engine: a named line per version (image), sharing the month x-axis.
for engine in ${engines}; do
  # Only versions present in the latest month are charted — a retired one would trail to a
  # false 0; a new one self-appears once it reaches the latest month.
  versions="$(awk -F, -v e="Test-${engine} (" -v last="${latest_month}" '
                NR>1 && $1==last && index($2, e)==1 {
                  v=$2; sub(/^.*\(/,"",v); sub(/\).*/,"",v); print v }' "${CSV}" | sort -u)"

  [ -n "${versions}" ] || continue

  printf '\n## %s\n\n```mermaid\nxychart-beta\n' "${engine}"
  printf '    title "%s — median minutes on main"\n' "${engine}"
  printf '    x-axis [%s]\n' "${months_axis}"
  printf '    y-axis "Median minutes"\n'

  for v in ${versions}; do
    # p50 per month aligned to the shared axis; months before this version ran get 0
    # (xychart-beta has no gap). The table shows true coverage.
    series="$(awk -F, -v job="Test-${engine} (${v})" -v ms="${months_csv}" '
      NR>1 && $2==job { p[$1]=$4 }
      END {
        n=split(ms, m, ",");
        for (i=1;i<=n;i++) printf "%s%s", (i>1?", ":""), (m[i] in p ? p[m[i]] : 0);
      }' "${CSV}")"
    printf '    line "%s" [%s]\n' "${v}" "${series}"
  done
  printf '```\n'
done

cat <<'EOF'

## Data

| Month | Job | Runs | Median min |
|-------|-----|-----:|-----------:|
EOF

awk -F, 'NR>1 {printf "| %s | %s | %s | %s |\n", $1, $2, $3, $4}' "${CSV}"
