services:

  # Dev Container
  codespace:
    container_name: codespace
    build:
      context: ./
      dockerfile: .devcontainer/images/devcontainer/Dockerfile
    restart: unless-stopped
    volumes:
      - .:/workspace:cached
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: host
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    privileged: true
