# Copyright (c) 2009-2011 VMware, Inc.

require 'rubygems'
require 'rake'
require 'rspec'
require 'rspec/core/rake_task'

RSpec::Core::RakeTask.new do |t|
  t.pattern = "**/*_spec.rb"
  t.rspec_opts = ["--format", "documentation", "--colour"]
end

namespace "spec" do
  task "rcov" do
    require "simplecov"

    SimpleCov.root('..')
    SimpleCov.coverage_dir(File.join("spec", "artifacts", "coverage"))
    SimpleCov.start do
      add_filter "/spec/"
      add_filter "/migrations/"
      RSpec::Core::Runner.disable_autorun!
      RSpec::Core::Runner.run(["."], STDERR, STDOUT)
    end
  end
end
