# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: logcache/egress.proto for package 'logcache.v1'

require 'grpc'
require 'logcache/egress_pb'

module Logcache
  module V1
    module Egress
      # The egress service is used to read data from the LogCache system.
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'logcache.v1.Egress'

        rpc :Read, ::Logcache::V1::ReadRequest, ::Logcache::V1::ReadResponse
        rpc :Meta, ::Logcache::V1::MetaRequest, ::Logcache::V1::MetaResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
