# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: logcache/egress.proto

require 'google/protobuf'

require 'loggregator-api/v2/envelope_pb'
require 'google/api/annotations_pb'


descriptor_data = "\n\x15logcache/egress.proto\x12\x0blogcache.v1\x1a!loggregator-api/v2/envelope.proto\x1a\x1cgoogle/api/annotations.proto\"\xb1\x01\n\x0bReadRequest\x12\x11\n\tsource_id\x18\x01 \x01(\t\x12\x12\n\nstart_time\x18\x02 \x01(\x03\x12\x10\n\x08\x65nd_time\x18\x03 \x01(\x03\x12\r\n\x05limit\x18\x04 \x01(\x03\x12\x31\n\x0e\x65nvelope_types\x18\x05 \x03(\x0e\x32\x19.logcache.v1.EnvelopeType\x12\x12\n\ndescending\x18\x06 \x01(\x08\x12\x13\n\x0bname_filter\x18\x07 \x01(\t\"@\n\x0cReadResponse\x12\x30\n\tenvelopes\x18\x01 \x01(\x0b\x32\x1d.loggregator.v2.EnvelopeBatch\"!\n\x0bMetaRequest\x12\x12\n\nlocal_only\x18\x01 \x01(\x08\"\x85\x01\n\x0cMetaResponse\x12\x31\n\x04meta\x18\x01 \x03(\x0b\x32#.logcache.v1.MetaResponse.MetaEntry\x1a\x42\n\tMetaEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12$\n\x05value\x18\x02 \x01(\x0b\x32\x15.logcache.v1.MetaInfo:\x02\x38\x01\"^\n\x08MetaInfo\x12\r\n\x05\x63ount\x18\x01 \x01(\x03\x12\x0f\n\x07\x65xpired\x18\x02 \x01(\x03\x12\x18\n\x10oldest_timestamp\x18\x03 \x01(\x03\x12\x18\n\x10newest_timestamp\x18\x04 \x01(\x03*N\n\x0c\x45nvelopeType\x12\x07\n\x03\x41NY\x10\x00\x12\x07\n\x03LOG\x10\x01\x12\x0b\n\x07\x43OUNTER\x10\x02\x12\t\n\x05GAUGE\x10\x03\x12\t\n\x05TIMER\x10\x04\x12\t\n\x05\x45VENT\x10\x05\x32\xbd\x01\n\x06\x45gress\x12`\n\x04Read\x12\x18.logcache.v1.ReadRequest\x1a\x19.logcache.v1.ReadResponse\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/api/v1/read/{source_id=**}\x12Q\n\x04Meta\x12\x18.logcache.v1.MetaRequest\x1a\x19.logcache.v1.MetaResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\x0c/api/v1/metaB7Z5code.cloudfoundry.org/go-log-cache/v3/rpc/logcache_v1b\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Logcache
  module V1
    ReadRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("logcache.v1.ReadRequest").msgclass
    ReadResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("logcache.v1.ReadResponse").msgclass
    MetaRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("logcache.v1.MetaRequest").msgclass
    MetaResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("logcache.v1.MetaResponse").msgclass
    MetaInfo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("logcache.v1.MetaInfo").msgclass
    EnvelopeType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("logcache.v1.EnvelopeType").enummodule
  end
end
