# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: logcache/ingress.proto for package 'logcache.v1'

require 'grpc'
require 'logcache/ingress_pb'

module Logcache
  module V1
    module Ingress
      # The ingress service is used to write data into the LogCache system.
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'logcache.v1.Ingress'

        # Send is used to emit Envelopes batches into LogCache. The RPC function
        # will not return until the data has been stored.
        rpc :Send, ::Logcache::V1::SendRequest, ::Logcache::V1::SendResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
