# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: logcache/ingress.proto

require 'google/protobuf'

require 'loggregator-api/v2/envelope_pb'


descriptor_data = "\n\x16logcache/ingress.proto\x12\x0blogcache.v1\x1a!loggregator-api/v2/envelope.proto\"S\n\x0bSendRequest\x12\x30\n\tenvelopes\x18\x01 \x01(\x0b\x32\x1d.loggregator.v2.EnvelopeBatch\x12\x12\n\nlocal_only\x18\x02 \x01(\x08\"\x0e\n\x0cSendResponse2H\n\x07Ingress\x12=\n\x04Send\x12\x18.logcache.v1.SendRequest\x1a\x19.logcache.v1.SendResponse\"\x00\x42\x37Z5code.cloudfoundry.org/go-log-cache/v3/rpc/logcache_v1b\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Logcache
  module V1
    SendRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("logcache.v1.SendRequest").msgclass
    SendResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("logcache.v1.SendResponse").msgclass
  end
end
