# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: log-cache/api/v1/promql.proto for package 'logcache.v1'

# See README.md in this directory for the commands used to generate this file

require 'grpc'
require 'logcache/promql_pb'

module Logcache
  module V1
    module PromQLQuerier
      # The PromQLQuerier service is used to query PromQL data from the LogCache system.
      class Service
        include GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'logcache.v1.PromQLQuerier'

        rpc :InstantQuery, PromQL::InstantQueryRequest, PromQL::InstantQueryResult
        rpc :RangeQuery, PromQL::RangeQueryRequest, PromQL::RangeQueryResult
      end

      Stub = Service.rpc_stub_class
    end
  end
end
