# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: egress.proto for package 'logcache.v1'

# See README.md in this directory for the commands used to generate this file

require 'grpc'
require 'logcache/egress_pb'

module Logcache
  module V1
    module Egress
      # The egress service is used to read data from the LogCache system.
      class Service
        include GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'logcache.v1.Egress'

        rpc :Read, ReadRequest, ReadResponse
        rpc :Meta, MetaRequest, MetaResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
