# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: logcache/orchestration.proto for package 'logcache.v1'

require 'grpc'
require 'logcache/orchestration_pb'

module Logcache
  module V1
    module Orchestration
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'logcache.v1.Orchestration'

        rpc :AddRange, ::Logcache::V1::AddRangeRequest, ::Logcache::V1::AddRangeResponse
        rpc :RemoveRange, ::Logcache::V1::RemoveRangeRequest, ::Logcache::V1::RemoveRangeResponse
        rpc :ListRanges, ::Logcache::V1::ListRangesRequest, ::Logcache::V1::ListRangesResponse
        rpc :SetRanges, ::Logcache::V1::SetRangesRequest, ::Logcache::V1::SetRangesResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
