# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: logcache/orchestration.proto

require 'google/protobuf'


descriptor_data = "\n\x1clogcache/orchestration.proto\x12\x0blogcache.v1\"#\n\x05Range\x12\r\n\x05start\x18\x01 \x01(\x04\x12\x0b\n\x03\x65nd\x18\x02 \x01(\x04\",\n\x06Ranges\x12\"\n\x06ranges\x18\x01 \x03(\x0b\x32\x12.logcache.v1.Range\"4\n\x0f\x41\x64\x64RangeRequest\x12!\n\x05range\x18\x01 \x01(\x0b\x32\x12.logcache.v1.Range\"\x12\n\x10\x41\x64\x64RangeResponse\"7\n\x12RemoveRangeRequest\x12!\n\x05range\x18\x01 \x01(\x0b\x32\x12.logcache.v1.Range\"\x15\n\x13RemoveRangeResponse\"\x13\n\x11ListRangesRequest\"8\n\x12ListRangesResponse\x12\"\n\x06ranges\x18\x01 \x03(\x0b\x32\x12.logcache.v1.Range\"\x91\x01\n\x10SetRangesRequest\x12\x39\n\x06ranges\x18\x01 \x03(\x0b\x32).logcache.v1.SetRangesRequest.RangesEntry\x1a\x42\n\x0bRangesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\"\n\x05value\x18\x02 \x01(\x0b\x32\x13.logcache.v1.Ranges:\x02\x38\x01\"\x13\n\x11SetRangesResponse2\xcd\x02\n\rOrchestration\x12I\n\x08\x41\x64\x64Range\x12\x1c.logcache.v1.AddRangeRequest\x1a\x1d.logcache.v1.AddRangeResponse\"\x00\x12R\n\x0bRemoveRange\x12\x1f.logcache.v1.RemoveRangeRequest\x1a .logcache.v1.RemoveRangeResponse\"\x00\x12O\n\nListRanges\x12\x1e.logcache.v1.ListRangesRequest\x1a\x1f.logcache.v1.ListRangesResponse\"\x00\x12L\n\tSetRanges\x12\x1d.logcache.v1.SetRangesRequest\x1a\x1e.logcache.v1.SetRangesResponse\"\x00\x42\x37Z5code.cloudfoundry.org/go-log-cache/v3/rpc/logcache_v1b\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Logcache
  module V1
    Range = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("logcache.v1.Range").msgclass
    Ranges = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("logcache.v1.Ranges").msgclass
    AddRangeRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("logcache.v1.AddRangeRequest").msgclass
    AddRangeResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("logcache.v1.AddRangeResponse").msgclass
    RemoveRangeRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("logcache.v1.RemoveRangeRequest").msgclass
    RemoveRangeResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("logcache.v1.RemoveRangeResponse").msgclass
    ListRangesRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("logcache.v1.ListRangesRequest").msgclass
    ListRangesResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("logcache.v1.ListRangesResponse").msgclass
    SetRangesRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("logcache.v1.SetRangesRequest").msgclass
    SetRangesResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("logcache.v1.SetRangesResponse").msgclass
  end
end
