# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: logcache/promql.proto for package 'logcache.v1'

require 'grpc'
require 'logcache/promql_pb'

module Logcache
  module V1
    module PromQLQuerier
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'logcache.v1.PromQLQuerier'

        rpc :InstantQuery, ::Logcache::V1::PromQL::InstantQueryRequest, ::Logcache::V1::PromQL::InstantQueryResult
        rpc :RangeQuery, ::Logcache::V1::PromQL::RangeQueryRequest, ::Logcache::V1::PromQL::RangeQueryResult
      end

      Stub = Service.rpc_stub_class
    end
  end
end
