type: object
properties:
  var:
    type: object
    description: Environment variables that are associated with the given app; keys and values are strings
    additionalProperties:
      type: [string, "null"]
  links:
    type: object
    description: Links to related resources
    properties:
      self:
        $ref: './Link.yaml'
        description: The URL to get the environment variables for this app
      app:
        $ref: './Link.yaml'
        description: The URL to get the app for these environment variables
description: The environment variables that are associated with the given app
