type: object
allOf:
  - $ref: './BaseSchema.yaml'
  - properties:
      guid:
        type: string
        format: uuid
        description: Unique identifier for the build
      created_at:
        type: string
        format: date-time
        description: The time with zone when the build was created
      updated_at:
        type: string
        format: date-time
        description: The time with zone when the build was last updated
      state:
        type: string
        description: State of the build; valid states are `STAGING`, `STAGED`, or `FAILED`
        enum:
          - STAGING
          - STAGED
          - FAILED
      staging_memory_in_mb:
        type: [integer, "null"]
        description: Memory in MB allocated for staging of the build
      staging_disk_in_mb:
        type: [integer, "null"]
        description: Disk space in MB allocated for staging of the build
      staging_log_rate_limit_bytes_per_second:
        type: [integer, "null"]
        description: Log rate limit in bytes per second allocated for staging of the build
      error:
        type: [string, 'null']
        description: A string describing errors during the build process
      lifecycle:
        $ref: './Lifecycle.yaml'
        description: Provides the lifecycle object to use during staging; this will override the build's application's default lifecycle for this build
      package:
        type: object
        description: The package that is the input to the staging process
        properties:
          guid:
            type: string
            format: uuid
            description: The guid of the package that is the input to the staging process
      droplet:
        type: [object, 'null']
        description: A resulting droplet from the staging process; `droplet` will be `null` if staging has not completed
        properties:
          guid:
            type: string
            format: uuid
            description: The guid of the droplet resulting from the staging process
      created_by:
        type: object
        description: The user that created the build
        properties:
          guid:
            type: string
            description: The guid of the user that created the build
          name:
            type: [string, "null"]
            description: The name of the user that created the build
          email:
            type: [string, "null"]
            description: The email of the user that created the build
      relationships:
        type: object
        description: Relationships to other resources
        properties:
          app:
            $ref: './RelationshipToOne.yaml'
            description: The app the build belongs to
      metadata:
        $ref: './Metadata.yaml'
        description: |-
          `labels`: Labels applied to the build

          `annotations`: Annotations applied to the build
      links:
        type: object
        description: Links to related resources
        properties:
          self:
            $ref: './Link.yaml'
            description: The URL to get this build
          app:
            $ref: './Link.yaml'
            description: The URL to get the app for this build
          droplet:
            $ref: './Link.yaml'
            description: The URL to get the droplet resulting from this build; only present once staging has completed
description: |-
  Builds represent the process of staging an application package. There are two types ([lifecycles](#lifecycles)) of builds: buildpack and docker.

  After an [application](#apps) is created and [packages](#packages) are uploaded, a build resource can be created to initiate the staging process. A successful build results in a [droplet](#droplets).
