type: object
allOf:
  - $ref: './BaseSchema.yaml'
  - properties:
      type:
        type: string
        description: Package type; valid values are `bits`, `docker`
        enum:
          - bits
          - docker
      data:
        type: object
        description: |-
          Data for package type.

          **Bits package data**

          A bits package is used to upload source code for an app to. The bits package will provide an `upload` link to which a zip file should be uploaded. Bits packages carry `data.error` and `data.checksum`.

          **Docker package data**

          A Docker package references a Docker image from a registry. Docker packages carry `data.image`, `data.username`, and `data.password`.
        properties:
          error:
            type: [string, 'null']
            description: If an error occurs this field will contain the error message
          checksum:
            type: object
            description: The checksum of the uploaded bits
            properties:
              type:
                type: string
                description: 'The checksum type, for example: `sha256`'
              value:
                type: [string, 'null']
                description: The checksum value; this will be populated after bits are uploaded
          image:
            type: string
            description: The registry address of the image
          username:
            type: [string, "null"]
            description: The username for the image's registry
          password:
            type: [string, "null"]
            description: The password for the image's registry
      state:
        type: string
        description: State of the package; valid states are `AWAITING_UPLOAD`, `PROCESSING_UPLOAD`, `READY`, `FAILED`, `COPYING`, `EXPIRED`
        enum:
          - AWAITING_UPLOAD
          - PROCESSING_UPLOAD
          - READY
          - FAILED
          - COPYING
          - EXPIRED
      relationships:
        type: object
        description: The relationships of the package
        properties:
          app:
            $ref: './RelationshipToOne.yaml'
            description: The app the package belongs to
      metadata:
        $ref: './Metadata.yaml'
        description: Labels and annotations applied to the package
      links:
        type: object
        description: Links to related resources
        properties:
          self:
            $ref: './Link.yaml'
            description: The URL to get this package
          upload:
            $ref: './Link.yaml'
            description: The URL to upload the package bits; present only on packages of type `bits`
          download:
            $ref: './Link.yaml'
            description: The URL to download the package bits; present only on packages of type `bits`
          app:
            $ref: './Link.yaml'
            description: The URL to get the app the package belongs to
description: |-
  A package is an application's 'source code'; either raw bits for your application or a pointer to these bits.

  In Cloud Foundry, packages are staged to produce an executable droplet. We currently support raw bits and Docker packages.
