$LOAD_PATH.unshift(File.expand_path('models', __dir__))

require 'diego/bbs/models/actions_pb'
require 'diego/bbs/models/actual_lrp_pb'
require 'diego/bbs/models/actual_lrp_requests_pb'
require 'diego/bbs/models/cached_dependency_pb'
require 'diego/bbs/models/cells_pb'
require 'diego/bbs/models/desired_lrp_pb'
require 'diego/bbs/models/desired_lrp_requests_pb'
require 'diego/bbs/models/domain_pb'
require 'diego/bbs/models/environment_variables_pb'
require 'diego/bbs/models/error_pb'
require 'diego/bbs/models/evacuation_pb'
require 'diego/bbs/models/events_pb'
require 'diego/bbs/models/modification_tag_pb'
require 'diego/bbs/models/network_pb'
require 'diego/bbs/models/ping_pb'
require 'diego/bbs/models/security_group_pb'
require 'diego/bbs/models/task_pb'
require 'diego/bbs/models/task_requests_pb'
require 'diego/bbs/models/volume_mount_pb'

require 'diego/bbs/error_types'
