name: Deploy CF API V3 OpenAPI Documentation

on:
  push:
    branches:
      - main
    paths:
      - 'docs/openapi/**'
      - '.github/workflows/openapi_deploy.yml'
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    container:
      image: node:24-alpine
    defaults:
      run:
        working-directory: docs/openapi
    permissions:
      contents: write
      id-token: write
      pages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        run: |
          apk add python3 make g++ git tar
          yarn install
      - name: Build
        run: |
          yarn build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs/openapi/dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
