# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: locket.proto for package 'models'

require 'grpc'
require 'locket/locket_pb'

module Models
  module Locket
    class Service
      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'models.Locket'

      rpc :Lock, LockRequest, LockResponse
      rpc :Fetch, FetchRequest, FetchResponse
      rpc :Release, ReleaseRequest, ReleaseResponse
      rpc :FetchAll, FetchAllRequest, FetchAllResponse
    end

    Stub = Service.rpc_stub_class
  end
end
