# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: locket/locket.proto

require 'google/protobuf'


descriptor_data = "\n\x13locket/locket.proto\x12\x06models\"l\n\x08Resource\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05owner\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\t\x12\x10\n\x04type\x18\x04 \x01(\tB\x02\x18\x01\x12#\n\ttype_code\x18\x05 \x01(\x0e\x32\x10.models.TypeCode\"I\n\x0bLockRequest\x12\"\n\x08resource\x18\x01 \x01(\x0b\x32\x10.models.Resource\x12\x16\n\x0ettl_in_seconds\x18\x02 \x01(\x03\"\x0e\n\x0cLockResponse\"4\n\x0eReleaseRequest\x12\"\n\x08resource\x18\x01 \x01(\x0b\x32\x10.models.Resource\"\x11\n\x0fReleaseResponse\"\x1b\n\x0c\x46\x65tchRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"3\n\rFetchResponse\x12\"\n\x08resource\x18\x01 \x01(\x0b\x32\x10.models.Resource\"H\n\x0f\x46\x65tchAllRequest\x12\x10\n\x04type\x18\x01 \x01(\tB\x02\x18\x01\x12#\n\ttype_code\x18\x02 \x01(\x0e\x32\x10.models.TypeCode\"7\n\x10\x46\x65tchAllResponse\x12#\n\tresources\x18\x01 \x03(\x0b\x32\x10.models.Resource*/\n\x08TypeCode\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x08\n\x04LOCK\x10\x01\x12\x0c\n\x08PRESENCE\x10\x02\x32\xf4\x01\n\x06Locket\x12\x33\n\x04Lock\x12\x13.models.LockRequest\x1a\x14.models.LockResponse\"\x00\x12\x36\n\x05\x46\x65tch\x12\x14.models.FetchRequest\x1a\x15.models.FetchResponse\"\x00\x12<\n\x07Release\x12\x16.models.ReleaseRequest\x1a\x17.models.ReleaseResponse\"\x00\x12?\n\x08\x46\x65tchAll\x12\x17.models.FetchAllRequest\x1a\x18.models.FetchAllResponse\"\x00\x62\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Models
  Resource = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("models.Resource").msgclass
  LockRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("models.LockRequest").msgclass
  LockResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("models.LockResponse").msgclass
  ReleaseRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("models.ReleaseRequest").msgclass
  ReleaseResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("models.ReleaseResponse").msgclass
  FetchRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("models.FetchRequest").msgclass
  FetchResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("models.FetchResponse").msgclass
  FetchAllRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("models.FetchAllRequest").msgclass
  FetchAllResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("models.FetchAllResponse").msgclass
  TypeCode = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("models.TypeCode").enummodule
end
