# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: locket/locket.proto for package 'models'

require 'grpc'
require 'locket/locket_pb'

module Models
  module Locket
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'models.Locket'

      rpc :Lock, ::Models::LockRequest, ::Models::LockResponse
      rpc :Fetch, ::Models::FetchRequest, ::Models::FetchResponse
      rpc :Release, ::Models::ReleaseRequest, ::Models::ReleaseResponse
      rpc :FetchAll, ::Models::FetchAllRequest, ::Models::FetchAllResponse
    end

    Stub = Service.rpc_stub_class
  end
end
